dist: xenial
language: generic
addons:
  snaps:
  - name: hugo
    channel: extended
script:
- hugo --minify
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  fqdn: food.ttp.sh
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: C1j1wV/NuYYM4wtsFy0QEMM2dp9SXaLN2O1+QNCrcIfz8nqYRJn0BFpbZ4XaphViqWFtLLRGAJcIB3XVT6Y5mzcIKHYfi7O3cd5clAv+sJVKfJ2aX050Wlk9VKxkECXms+6wffC1UfqhcdZnm5IOkI8mddvUuwk1TOffgt8aY6Vi+9JfAqtWp9m1Eh3Yk+Ph6yBPSoAvj0f/4VC1jEGz4M9zD33e8hCxWpdd6OwLU0jbu6glnIAeZcR7e/45pjrNQ7fQZtol6237552GaO80lCCLgEgrhZzLFGTfqLtCxm//nkevt341+A3XupcGXbPAy46zfRLEU0uWwWXxUXSnzRfzVbKYMlUB+6l1Lgttg3WWWfCVmDrDFaBF7uqYLdbdhUcwlpZJHbUUDvwO8PtsNVNpRqjdySpeG+Q5SEZsbluMrfcBnvnnx2UiUYMb4Do5x8QBP+NEl++RKw0gB0At9DHmggnmgLnNv5qhHrtdNeAbNkBADK8ru0g8ELLNE3l2Pc0ZidYbkiUJg5GZkG8C1/EAhebTxcf8CZoNbFv1mAEifyjw34IfmCsQOVqB7LRQa/rCOzSWq4TrobuOyOQcn2qVPeJGtJSg8ToBusxMLima7f0dqShFfe/7C1H1m/mfcHi7HPvg8qgNfQWnm3obx1T+QjrjEEqYQplmNTm2VC8=
