baseURL = "https://toms.cooking/"
# baseURL = "http://localhost:8080/"
languageCode = "en-au"

title = "Tom's Cooking"
paginate = 12

googleAnalytics = "UA-135024983-1"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[permalinks]
recipes = "/:title/"

[outputs]
home = [ "html", "rss", "json"]

[taxonomies]
  tag = "tags"